export const materials = [
  { id: 1, name: "Oro" },
  { id: 2, name: "Plata" },
  { id: 3, name: "Platino" },
  { id: 4, name: "Titanio" },
  { id: 5, name: "Acero Inoxidable" },
  { id: 6, name: "Cobre" },
  { id: 7, name: "Bronce" },
  { id: 8, name: "Aluminio" },
  { id: 9, name: "Piedra preciosa" },
  { id: 10, name: "Perla" },
  { id: 11, name: "Jade" },
  { id: 12, name: "Ágata" },
  { id: 13, name: "Cuarzo" },
  { id: 14, name: "Onyx" },
  { id: 15, name: "Turquesa" },
  { id: 16, name: "Zirconia" },
  { id: 17, name: "Diamante" },
  { id: 18, name: "Espinela" },
  { id: 19, name: "Granate" },
  { id: 20, name: "Rubí" },
  { id: 21, name: "Esmeralda" },
  { id: 22, name: "Sodalita" },
  { id: 23, name: "Lapislázuli" },
  { id: 24, name: "Cristal de roca" },
  { id: 25, name: "Coral" },
  { id: 26, name: "Ámbar" },
  { id: 27, name: "Obsidiana" },
  { id: 28, name: "Malaquita" },
  { id: 29, name: "Peridot" },
  { id: 30, name: "Citrino" },
  { id: 31, name: "Topacio" },
  { id: 32, name: "Zafiro" },
  { id: 33, name: "Carmesi" },
  { id: 34, name: "Cobalto" },
  { id: 35, name: "Amaranto" },
  { id: 36, name: "Acero" },
  { id: 37, name: "Acero Negro" },
];
