export const materials = [
  { id: 1, name: "Ágata" },
  { id: 2, name: "Ámbar" },
  { id: 3, name: "Acero" },
  { id: 4, name: "Acero Inoxidable" },
  { id: 5, name: "Acero Negro" },
  { id: 6, name: "Aluminio" },
  { id: 7, name: "Amaranto" },
  { id: 8, name: "Bronce" },
  { id: 9, name: "Carmesi" },
  { id: 10, name: "Citrino" },
  { id: 11, name: "Cobalto" },
  { id: 12, name: "Cobre" },
  { id: 13, name: "Coral" },
  { id: 14, name: "Cristal de roca" },
  { id: 15, name: "Cuarzo" },
  { id: 16, name: "Diamante" },
  { id: 17, name: "Esmeralda" },
  { id: 18, name: "Espinela" },
  { id: 19, name: "Granate" },
  { id: 20, name: "Jade" },
  { id: 21, name: "Lapislázuli" },
  { id: 22, name: "Malaquita" },
  { id: 23, name: "Onyx" },
  { id: 24, name: "Oro" },
  { id: 25, name: "Peridot" },
  { id: 26, name: "Perla" },
  { id: 27, name: "Piedra preciosa" },
  { id: 28, name: "Plata" },
  { id: 29, name: "Platino" },
  { id: 30, name: "Rubí" },
  { id: 31, name: "Sodalita" },
  { id: 32, name: "Titanio" },
  { id: 33, name: "Topacio" },
  { id: 34, name: "Turquesa" },
  { id: 35, name: "Zafiro" },
  { id: 36, name: "Zirconia" },
];

export const IGV = 0.18;

export enum PaymentMethod {
  CASH = "CASH",
  CARD = "CARD",
  YAPE = "YAPE",
  PLIN = "PLIN",
  TRANSFER = "TRANSFER",
}

export const PaymentMethodLabels: Record<PaymentMethod, string> = {
  [PaymentMethod.CASH]: "Efectivo",
  [PaymentMethod.CARD]: "Tarjeta",
  [PaymentMethod.YAPE]: "Yape",
  [PaymentMethod.PLIN]: "Plin",
  [PaymentMethod.TRANSFER]: "Transferencia",
};
